import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "@/components";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const InterFont = Inter({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.className} min-h-svh grid grid-cols-app`}>
        <Sidebar />
        <main className="px-4 pb-12 pt-8">{children}</main>
      </body>
    </html>
  );
}
